// Dummy players
export const apiRes = [
  {
    player_id: 714,
    player_picture: "https://olympia.phoinix.ai/pictures/players/714.jpg",
    player_name_latin: "BEN YEDDER Wissam",
    player_name_arabic: "",
    rank: 2,
    rank_en: "2nd",
    rank_fr: "2e",
    rank_ar: "\u0662.",
    title_en: "2nd BEST SCORER WITH WEAKEST FOOT",
    title_fr: "2e MEILLEUR BUTEUR DU MAUVAIS PIED",
    title_ar: "\u0662. MEILLEUR BUTEUR DU MAUVAIS PIED",
    competition_en: "IN TOP 5 LEAGUES",
    competition_fr: "DANS LES CHAMPIONNATS DU TOP 5",
    competition_ar: "",
    standings: [
      {
        rank: 1,
        id: 741,
        picture: "https://olympia.phoinix.ai/pictures/players/741.jpg",
        name_latin: "DE BRUYNE Kevin",
        name_arabic: "",
        total: 9,
        main: 0,
      },
      {
        rank: 2,
        id: 714,
        picture: "https://olympia.phoinix.ai/pictures/players/714.jpg",
        name_latin: "BEN YEDDER Wissam",
        name_arabic: "",
        total: 9,
        main: 1,
      },
      {
        rank: 3,
        id: 464,
        picture: "https://olympia.phoinix.ai/pictures/players/464.jpg",
        name_latin: "LEWANDOWSKI Robert",
        name_arabic: "",
        total: 8,
        main: 0,
      },
    ],
  },
  {
    player_id: 1222,
    player_picture: "https://olympia.phoinix.ai/pictures/players/1222.jpg",
    player_name_latin: "DELORT Andy",
    player_name_arabic: "",
    rank: 2,
    rank_en: "2nd",
    rank_fr: "2e",
    rank_ar: "\u0662.",
    title_en: "2nd BEST QUICKEST PLAYER TO SCORE A HAT-TRICK",
    title_fr: "2e MEILLEUR JOUEUR LE PLUS RAPIDE \u00c0 MARQUER UN HAT-TRICK",
    title_ar: "\u0662. MEILLEUR ",
    competition_en: "IN TOP 5 LEAGUES",
    competition_fr: "DANS LES CHAMPIONNATS DU TOP 5",
    competition_ar: "",
    standings: [
      {
        rank: 1,
        id: 431,
        picture: "https://olympia.phoinix.ai/pictures/players/431.jpg",
        name_latin: "SCHICK Patrik",
        name_arabic: "",
        total: "418s",
        main: 0,
      },
      {
        rank: 2,
        id: 1222,
        picture: "https://olympia.phoinix.ai/pictures/players/1222.jpg",
        name_latin: "DELORT Andy",
        name_arabic: "",
        total: "466s",
        main: 1,
      },
      {
        rank: 3,
        id: 714,
        picture: "https://olympia.phoinix.ai/pictures/players/714.jpg",
        name_latin: "BEN YEDDER Wissam",
        name_arabic: "",
        total: "615s",
        main: 0,
      },
    ],
  },
  {
    player_id: 1222,
    player_picture: "https://olympia.phoinix.ai/pictures/players/1222.jpg",
    player_name_latin: "DELORT Andy",
    player_name_arabic: "",
    rank: 2,
    rank_en: "2nd",
    rank_fr: "2e",
    rank_ar: "\u0662.",
    title_en: "2nd QUICKEST PLAYER TO SCORE A HAT-TRICK",
    title_fr: "2e LE PLUS RAPIDE JOUEUR \u00c0 MARQUER UN TRIPL\u00c9",
    title_ar: "\u0662. LE PLUS RAPIDE ",
    competition_en: "IN TOP 5 LEAGUES",
    competition_fr: "DANS LES CHAMPIONNATS DU TOP 5",
    competition_ar: "",
    standings: [
      {
        rank: 1,
        id: 692,
        picture: "https://olympia.phoinix.ai/pictures/players/692.jpg",
        name_latin: "BENZEMA Karim",
        name_arabic: "",
        total: "11",
        main: 0,
      },
      {
        rank: 2,
        id: 1222,
        picture: "https://olympia.phoinix.ai/pictures/players/1222.jpg",
        name_latin: "DELORT Andy",
        name_arabic: "",
        total: "9",
        main: 1,
      },
      {
        rank: 3,
        id: 264,
        picture: "https://olympia.phoinix.ai/pictures/players/264.jpg",
        name_latin: "ARNAUTOVIC Marko",
        name_arabic: "",
        total: "7",
        main: 0,
      },
    ],
  },
  {
    player_id: 571,
    player_picture: "https://olympia.phoinix.ai/pictures/players/571.jpg",
    player_name_latin: "CORREA Joaquin",
    player_name_arabic: "",
    rank: 3,
    rank_en: "3rd",
    rank_fr: "3e",
    rank_ar: "\u0663.",
    title_en: "3rd QUICKEST PLAYER TO SCORE A BRACE",
    title_fr: "3e LE PLUS RAPIDE JOUEUR \u00c0 MARQUER UN DOUBL\u00c9",
    title_ar: "\u0663. LE PLUS RAPIDE ",
    competition_en: "IN TOP 5 LEAGUES",
    competition_fr: "DANS LES CHAMPIONNATS DU TOP 5",
    competition_ar: "",
    standings: [
      {
        rank: 1,
        id: 2048,
        picture: "https://olympia.phoinix.ai/pictures/players/2048.jpg",
        name_latin: "BERGWIJN Steven",
        name_arabic: "",
        total: "78s",
        main: 0,
      },
      {
        rank: 2,
        id: 431,
        picture: "https://olympia.phoinix.ai/pictures/players/431.jpg",
        name_latin: "SCHICK Patrik",
        name_arabic: "",
        total: "104s",
        main: 0,
      },
      {
        rank: 3,
        id: 571,
        picture: "https://olympia.phoinix.ai/pictures/players/571.jpg",
        name_latin: "CORREA Joaquin",
        name_arabic: "",
        total: "118s",
        main: 1,
      },
    ],
  },
];
export const players = [
  {
    key: 0,
    url: "https://olympia.phoinix.ai/pictures/players/23.jpg",
    name: "Liva0",
    additionalInfo: {
      title: "Karim Ben Zima",
      description: "BEST SOCCER WITH WEAKEST FOOT",
      link: { url: "", text: "IN TOP 5 LEAGUES" },
      top3: [
        { rank: 1, name: "Messi", goals: 9 },
        { rank: 2, name: "Cristiano Ronaldo", goals: 7 },
        { rank: 3, name: "Mbapee", goals: 4 },
      ],
    },
  },
  {
    key: 1,
    url: "https://olympia.phoinix.ai/pictures/players/60.jpg",
    name: "Liva1",
    additionalInfo: {
      title: "Livandowski",
      description: "BEST SOCCER WITH WEAKEST FOOT",
      link: { url: "", text: "IN TOP 5 LEAGUES" },
      top3: [
        { rank: 1, name: "Livandowski", goals: 9 },
        { rank: 2, name: "Mohamed Salah", goals: 7 },
        { rank: 3, name: "Sadio Mane", goals: 4 },
      ],
    },
  },
  {
    key: 2,
    url: "https://olympia.phoinix.ai/pictures/players/11.jpg",
    name: "Liva2",
  },
  {
    key: 3,
    url: "https://olympia.phoinix.ai/pictures/players/15.jpg",
    name: "Liva3",
  },
];
//Dummy clubs
export const clubs = [
  {
    key: 0,
    url: "https://olympia.phoinix.ai/pictures/clubs/23.png",
    name: "Liva0",
    additionalInfo: {
      title: "Karim Ben Zima",
      description: "BEST SOCCER WITH WEAKEST FOOT",
      link: { url: "", text: "IN TOP 5 LEAGUES" },
      top3: [
        { rank: 1, name: "Messi", goals: 9 },
        { rank: 2, name: "Cristiano Ronaldo", goals: 7 },
        { rank: 3, name: "Mbapee", goals: 4 },
      ],
    },
  },
  {
    key: 1,
    url: "https://olympia.phoinix.ai/pictures/clubs/60.png",
    name: "Liva1",
    additionalInfo: {
      title: "Livandowski",
      description: "BEST SOCCER WITH WEAKEST FOOT",
      link: { url: "", text: "IN TOP 5 LEAGUES" },
      top3: [
        { rank: 1, name: "Livandowski", goals: 9 },
        { rank: 2, name: "Mohamed Salah", goals: 7 },
        { rank: 3, name: "Sadio Mane", goals: 4 },
      ],
    },
  },
  {
    key: 2,
    url: "https://olympia.phoinix.ai/pictures/clubs/11.png",
    name: "Liva2",
  },
  {
    key: 3,
    url: "https://olympia.phoinix.ai/pictures/clubs/15.png",
    name: "Liva3",
  },
];
export const mostValuablePlayer = {
  title: "Most Valuable Player",
  representerUrl: "https://olympia.phoinix.ai/pictures/players/15.jpg",
  profileName: "LEWANDOWSKI Robert",
  flags: [
    { url: "https://olympia.phoinix.ai/pictures/clubs/61.png", key: 1 },
    { url: "https://olympia.phoinix.ai/pictures/nations/174.png", key: 2 },
  ],
  ratings: [
    { name: "OLYMPIA RATING", note: "9.2", key: 1 },
    { name: "MOTM Awards", note: "8.2", key: 2 },
    { name: "Played Games", note: "7", key: 3 },
    { name: "Stat 1", note: "3.5", key: 4 },
    { name: "Stat 2", note: "9.5", key: 5 },
  ],
};
export const mostValuableGoalKeeper = {
  title: "Most Valuable Goalkeper",
  representerUrl: "https://olympia.phoinix.ai/pictures/players/11.jpg",
  profileName: "Messi",
  flags: [
    { url: "https://olympia.phoinix.ai/pictures/clubs/61.png", key: 1 },
    { url: "https://olympia.phoinix.ai/pictures/nations/174.png", key: 2 },
  ],
  ratings: [
    { name: "OLYMPIA RATING", note: "7.2", key: 1 },
    { name: "MOTM Awards", note: "9.2", key: 2 },
    { name: "Played Games", note: "7.4", key: 3 },
    { name: "Stat 1", note: "3.5", key: 4 },
    { name: "Stat 2", note: "9.5", key: 5 },
  ],
};

export default { players, clubs, mostValuableGoalKeeper, mostValuablePlayer };
